version: '3.8'

services:
  # http://localhost:18081
  jobmanager:
    image: flink:1.17-scala_2.12
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "18081:8081" # Flink Web UI
    networks:
      - flink-network
    command: jobmanager
  
  taskmanager:
    image: flink:1.17-scala_2.12
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    ports:
      - "6121:6121" # RPC port
      - "6122:6122" # Data transfer port
    networks:
      - flink-network
    command: taskmanager
  
  kafka:
    image: landoop/fast-data-dev:latest
    container_name: kafka
    ports:
      # http://localhost:3030
      - "3030:3030" # Web UI
      - "8081:8081" # Schema registry
      - "8082:8082" # Kafka REST proxy
      - "8083:8083" # Kafka connect distributed
      - "9092:9092" # Kafka broker
      - "2181:2181" # ZooKeeper
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0 # Disable Running tests so the cluster starts faster
      DEBUG: 1
      SAMPLEDATA: 1 # Disable creating sample topics
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  kafka_data:

networks:
  flink-network:
  kafka-network:
